# Захист практикуму №2 
# Абраменко Микити Олександровича, студента групи КА-01
# 1 варіант - Створення тензорів в TensorFlow.

In [33]:
import tensorflow as tf
import numpy as np

Є декілька способів створення тензорів в Tensorflow:
1. Просте створення зі списку або масиву NumPy, важливим зауваженням є те, що вони як і масиви NumPy повинні мати один тип данних (хоча і є шляхи як це можна обійти, але зазвичай цього не роблять, адже це заважає головній особливості NumPy - швидким математичним операціям над матрицями)

In [34]:
a = np.array([1, 2, 3], dtype=np.int32)
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(t_a, t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32) tf.Tensor([4 5 6], shape=(3,), dtype=int32)


Як ми бачимо вони перейняли типи данних, схоже до масивів NumPy ми можемо далі побачити їх властивості:

In [35]:
print(f'shape: {t_a.shape}, types of elements in it: {t_a.dtype}, number of axes: {t_a.ndim}')

shape: (3,), types of elements in it: <dtype: 'int32'>, number of axes: 1


2. Constant (не можна змінювати) та Variable (можна змінювати значення у ньому), такими тензорами можна створювати ваги для нейронних мереж, ваги які не потрібно навчати - constant, які підлягають навчанню - variable:

In [36]:
t_c = tf.constant([[1, 2],
                    [3, 4],
                    [5, 6]], dtype=tf.float16)

print(t_c, '\n')

try: 
    t_c[0][0].assign(10)
except Exception as e:
    print(f"{type(e).__name__}: {e}")

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16) 

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


In [37]:
t_v = tf.Variable([[3, 4],
                    [5, 6],
                    [7, 8]], dtype=tf.float16)

print(t_v, '\n')

try: 
    t_v[0, 0].assign(10)
    print(t_v)
except Exception as e: print(e)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float16, numpy=
array([[3., 4.],
       [5., 6.],
       [7., 8.]], dtype=float16)> 

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float16, numpy=
array([[10.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]], dtype=float16)>


3. Базові тензори вимагають правильної "прямокутної" форми, але у tensorflow, також є класси які дозволяють обійти це обмеження:
* RaggedTensor
* SparseTensor

In [38]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

try:
    tensor = tf.constant(ragged_list)
except Exception as e:
    print(f"{type(e).__name__}: {e}")
    
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor, '\n', ragged_tensor.shape)

ValueError: Can't convert non-rectangular Python sequence to Tensor.
<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]> 
 (4, None)


Як ми можемо помітити такий тензор має осі з невідомою довжиною

In [39]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


Такі тензори іноді використовують для зберігання пам'яті, наприклад коли змінні були закодовані через OHE

Якщо тензор потрібно повернути у вигляді масиву NumPy, то можна використати метод .numpy(), або np.array(tensor):

In [40]:
print(t_a.numpy(), type(t_a.numpy()))

[1 2 3] <class 'numpy.ndarray'>


In [41]:
print(np.array(t_a), type(np.array(t_a)))

[1 2 3] <class 'numpy.ndarray'>
