# 3 варіант

Застосування математичних операцій до тензорів.

У тензорфлоу математичні операції над тензорами схожі на аналоги з Numpy

In [23]:
import tensorflow as tf

## Базові математичні операції над тензорами:

### Додавання

In [24]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Або - tf.ones([2,2])

tf.add(a, b) # або a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

### поелементне множення 

In [25]:
tf.multiply(a, b) # a * b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

### матричне множення 

In [26]:
tf.matmul(a, b) # a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]])>

### віднімання 

In [27]:
tf.subtract(a, b) # a - b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]])>

### ділення 

In [28]:
tf.divide(a, b) # a / b

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

### tensordot

In [29]:
tf.tensordot(a, b, axes=0) # зовнішній добуток, тензор порядку 4

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2]]],


       [[[3, 3],
         [3, 3]],

        [[4, 4],
         [4, 4]]]])>

In [30]:
tf.tensordot(a, b, axes=1) # так ми отримуємо матричне множення 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]])>

### Транспозиція

In [31]:
tf.constant([[1, 2],
            [3, 4],
            [5 ,6]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [32]:
tf.transpose(tf.constant([[1, 2],
                        [3, 4],
                        [5 ,6]]))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

Та багато інших, tensorflow має стандартні математичні операції над тензорами, і також багато інших операцій спеціально для машинного навчання