# Башинський Владислав КА-05 
13 варіант: Об’єкти Variable бібліотеки TensorFlow для збереження і оновлення параметрів моделі.

In [1]:
import tensorflow as tf

Змінні створюються і відстежуються за допомогою класу tf.Variable у Tensorflow. 

tf.Variable являє собою тензор, значення якого можна змінити, запустивши над ним операції, навідміну від tf.constant, значення якого змінити не можна.

Конкретні операції дають змогу читати і змінювати значення цього тензора. Бібліотеки вищого рівня, як-от tf.keras використовують tf.Variable для зберігання параметрів моделі.

## Створення 

Для того щоб створити tf.Variable потрібно вказати початкове значення, сам tf.Variable буде мати той самий тип даних, що і значення при ініціалізації

In [2]:
my_variable = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

# Змінні можуть бути будь-яких типів, так само як і тензори
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

Змінна виглядає і діє як тензор і, по суті, є структурою даних, підтримуваною tf.Tensor.

 Як і тензори, вони мають dtype і форму, і їх можна експортувати в NumPy.

In [3]:
print("Shape: ", my_variable.shape)
print("DType: ", my_variable.dtype)
print("As NumPy: ", my_variable.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


In [4]:
print("Shape of bool: ", bool_variable.shape)
print("DType of bool: ", bool_variable.dtype)
print("Bool as NumPy: ", bool_variable.numpy())

Shape of bool:  (4,)
DType of bool:  <dtype: 'bool'>
Bool as NumPy:  [False False False  True]


In [5]:
print("Shape of complex: ", complex_variable.shape)
print("DType of complex: ", complex_variable.dtype)
print("Complex as NumPy: ", complex_variable.numpy())

Shape of complex:  (2,)
DType of complex:  <dtype: 'complex128'>
Complex as NumPy:  [5.+4.j 6.+1.j]


Більшість тензорних операцій працюють зі змінними, але змінні не можуть бути змінені на місці 

In [7]:
print("A variable:", my_variable)
print("\nViewed as a tensor:", tf.convert_to_tensor(my_variable))
print("\nIndex of highest value:", tf.argmax(my_variable))

# Це створює новий тензор, а не перероблює наявний
print("\nCopying and reshaping: ", tf.reshape(my_variable, [1,4]))
print("\nA variable:", my_variable)

A variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)

Copying and reshaping:  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)

A variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>


Створення нових змінних з наявних змінних дублює резервні тензори. Дві змінні не будуть використовувати одну й ту саму пам'ять.

In [8]:
a = tf.Variable([2.0, 3.0])
# Створити b на основі значення a
b = tf.Variable(a)
a.assign([5, 6])

# a і b відрізняються
print(a.numpy())
print(b.numpy())

# Існують і інші версії assign
print(a.assign_add([2,3]).numpy())  # [7. 9.]
print(a.assign_sub([7,9]).numpy())  # [0. 0.]

[5. 6.]
[2. 3.]
[7. 9.]
[0. 0.]


Цей тип данних зазвичай використовується для параметрів моделі які потребують навчання, але якщо ця змінна не потребує навчання їй можна присвоїти атрибут trainable = false при створенні

Прикладом змінної якій не потрібні градієнти і навчання - лічильник кроків навчання:

In [11]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2
tape.gradient(y, x)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [15]:
step_counter = tf.Variable(1., trainable=False)

with tf.GradientTape() as tape:
    y = step_counter**2

print(tape.gradient(y, step_counter))

None
